# Оценка ТЗ по меню виртуального ассистента

Запустите ячейки по порядку. Укажите `TZ_PATH` в папке `TZ` и при необходимости поменяйте модель.

Ключ `OPENAI_API_KEY` читается из `.env` в корне репозитория или `evaluator/.env` (приоритет у последнего).
Текст ТЗ передаётся в OpenAI API. Поддерживаются DOCX (включая таблицы), текстовые PDF, TXT и MD.
Сканы требуют предварительного OCR; рисунки и вложенные объекты DOCX автоматически не распознаются.

«Успешно проставлено» означает наличие одной из четырёх оценок, а не независимую проверку её правильности.
Уверенность — самооценка модели. Неясные требования помечаются «не определено».
Результаты требуют проверки аналитиком. Повторный запуск создаёт отдельную папку результатов.

In [ ]:
from pathlib import Path
_install_root = next(p for p in [Path.cwd().resolve(), *Path.cwd().resolve().parents]
                     if (p / "evaluator/requirements.txt").is_file())
_requirements = str(_install_root / "evaluator/requirements.txt")
%pip install -r "{_requirements}"

Зависимости устанавливаются в текущее ядро. После первой установки при необходимости перезапустите ядро.

In [1]:
from pathlib import Path
import sys
import os
from datetime import datetime, timezone
from uuid import uuid4

HERE = Path.cwd().resolve()
ROOT = next((p for p in [HERE, *HERE.parents] if (p / "evaluator/effort_evaluator.py").is_file()), None)
if ROOT is None:
    raise RuntimeError("Откройте ноутбук из корня репозитория или папки evalutator.")
sys.path.insert(0, str(ROOT / "evaluator"))
from effort_evaluator import load_menu, load_spec, evaluate, summarize, statistics, save_results, save_summary
from dotenv import dotenv_values
from openai import OpenAI
from IPython.display import display

# Настройки пользователя
MENU_PATH = ROOT / "evaluator/chatbot_virtual_assistant_effort_menu.csv"
TZ_DIR = ROOT / "evaluator/TZ"
TZ_PATH = TZ_DIR / "ТЗ - Сервис для создания виртуальных ассистентов (Electra 2.0).docx"
BATCH_SIZE = 7
MAX_SPEC_CHARS = 180_000  # Защита от переполнения контекста; ТЗ не обрезается.

config = {**dotenv_values(ROOT / ".env"), **dotenv_values(ROOT / "evaluator/.env")}
MODEL = config.get("OPENAI_EVALUATOR_MODEL") or config.get("OPENAI_LLM_MODEL") or "gpt-4.1-mini"
RUN_DIR = ROOT / "evaluator/results" / (datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ") + "_" + uuid4().hex[:8])

In [2]:
menu = load_menu(MENU_PATH)
text = load_spec(TZ_PATH, TZ_DIR)
print(f"ТЗ: {TZ_PATH.name}; символов: {len(text):,}; пунктов меню: {len(menu)}; модель: {MODEL}")
display(menu)
if len(text) > MAX_SPEC_CHARS:
    raise ValueError("ТЗ превышает MAX_SPEC_CHARS. Увеличьте лимит с учётом контекста модели.")

ТЗ: ТЗ - Сервис для создания виртуальных ассистентов (Electra 2.0).docx; символов: 36,361; пунктов меню: 42; модель: gpt-4.1-mini

,Блок,Компонент,Отсутствует,Small,Medium,Large
0,Каналы и интерфейсы,Текстовый веб-чат,Не нужен.,Готовый web-виджет или простая страница чата; ...,Кастомный UI в существующем продукте; авториза...,Полноценный омниканальный интерфейс с кастомны...
1,Каналы и интерфейсы,Мессенджеры и внешние каналы,Не нужны.,Один стандартный канал: Telegram / Slack / Tea...,"2–4 канала, единая логика сессий и пользовател...","Много каналов, contact-center/CRM, сложная мар..."
2,Каналы и интерфейсы,Мобильное приложение / SDK,Не требуется.,Интеграция в существующее приложение через Web...,"Нативная интеграция iOS/Android, push-уведомле...","Отдельный мобильный UX, offline/poor-network с..."
3,Голос,Голосовой ввод (Speech-to-Text),Не нужен.,"Стандартный SaaS STT (например, Whisper API / ...",On-prem / private cloud STT либо повышенные тр...,On-prem с высокими SLA и масштабом; специфичес...
4,Голос,Голосовой вывод (Text-to-Speech),Не нужен.,Стандартный SaaS TTS с готовым голосом.,On-prem/private deployment или кастомный голос...,Собственный/брендовый голос с датасетом и дооб...
5,Голос,Телефонный канал / телефония,Не нужен.,Подключение одного SIP/телефония-провайдера; в...,Интеграция с корпоративной телефонией/contact ...,Высоконагруженный voice-bot: тысячи параллельн...
6,LLM и диалог,Базовая LLM / генерация ответов,LLM не используется; ответы по фиксированным п...,"Одна облачная LLM через API, базовый system pr...","Несколько моделей/провайдеров, fallback, маршр...",On-prem/self-hosted LLM или сложный model gate...
7,LLM и диалог,Промптинг и управление поведением,Не требуется.,Один основной системный промпт и несколько про...,"Набор сценариев и ролей, structured outputs, p...","Большая prompt/agent policy-система, динамичес..."
8,LLM и диалог,Управление контекстом диалога,Каждое сообщение независимо.,Хранение последних N сообщений одной сессии.,"Суммаризация длинных диалогов, выделение факто...",Долгосрочная память по пользователю/организаци...
9,LLM и диалог,Сценарии / state machine,Свободный чат без фиксированных сценариев.,Несколько простых intent → response/action сце...,"Многошаговые бизнес-процессы с состояниями, ва...","Сложные динамические workflow, десятки процесс..."
10,LLM и диалог,Мультиязычность,Один язык.,"2–3 массовых языка, возможности базовой LLM до...","Много языков, отдельные промпты/KB, терминолог...","Редкие языки/диалекты, код-свитчинг, специализ..."
11,Знания и RAG,База знаний / RAG,Ответы не требуют внешних знаний.,Небольшой набор статичных документов; стандарт...,"Тысячи/десятки тысяч документов, несколько ист...","Очень большой/динамический корпус, multi-hop r..."
12,Знания и RAG,Источники данных для базы знаний,Нет источников.,Файлы PDF/DOCX/HTML или один простой источник.,"SharePoint/Confluence/Google Drive/БД/API, 2–5...","Много корпоративных систем, нестандартные исто..."
13,Знания и RAG,Обработка документов,Не требуется.,Текстовые PDF/DOCX/HTML без сложной структуры.,"OCR, таблицы, презентации, сложные PDF, извлеч...","Сканированные/низкокачественные документы, схе..."
14,Знания и RAG,Цитирование и доказательность ответов,Не требуется.,Ссылки на использованные документы/страницы.,"Точные цитаты/фрагменты, проверка groundedness...","Формальная трассируемость каждого утверждения,..."
15,Интеграции и действия,Интеграции с внешними системами,"Ассистент только отвечает, интеграций нет.",1–2 простых REST API с хорошей документацией.,"3–6 систем, OAuth/service accounts, нестандарт...","Много legacy/enterprise систем, SOAP/ESB/шины,..."
16,Интеграции и действия,Выполнение действий от имени пользователя,Только чтение/ответы.,"Простые безопасные действия: создать заявку, о...",Изменяющие операции с подтверждением пользоват...,Критичные бизнес-операции: финансовые/юридичес...
17,Интеграции и действия,Agentic tool use / выбор инструментов,Нет tool calling.,Небольшой фиксированный набор 1–3 инструментов...,"5–15 инструментов, планирование последовательн...","Большой динамический каталог инструментов, mul..."
18,Интеграции и действия,Human handoff / оператор,Не нужен.,Простая кнопка «позвать оператора» или создани...,Передача диалога и контекста в contact center/...,"Сложная маршрутизация по компетенциям/SLA, sup..."
19,Персонализация,Профиль и персонализация пользователя,Все пользователи получают одинаковые ответы.,"Использование нескольких полей профиля: имя, р...","Контекст из CRM/профиля, предпочтения, история...",Глубокая персонализация по поведению и истории...
20,Персонализация,Роли и права доступа,Авторизация и разграничение не нужны.,Обычная авторизация и 2–3 роли.,"SSO/OIDC/SAML, группы, RBAC, document-level AC...","Enterprise IAM: сложные иерархии, ABAC, delega..."
21,Безопасность,Защита от prompt injection / data leakage,Специальные меры не требуются.,"Базовые system rules, фильтрация известных опа...","Изоляция источников/инструментов, allowlists, ...","Высокорисковая среда: policy engine, sandboxin..."
22,Безопасность,PII / конфиденциальные данные,Персональные/секретные данные не обрабатываются.,Обычные персональные данные; шифрование и стан...,"Чувствительные данные, masking/redaction, data...",Регулируемые/особо чувствительные данные; стро...
23,Безопасность,Контент-фильтрация / moderation,Не требуется.,Готовый moderation API или простые правила.,"Собственные категории/политики, языки, moderat...","Высокорисковый домен, кастомные классификаторы..."
24,Безопасность,Аудит действий,Не нужен.,Логи запросов/ответов и технических ошибок.,"Версионированные логи промптов, retrieval, too...","Полный tamper-resistant audit trail, юридическ..."
25,Модели и ML,Fine-tuning / дообучение LLM,Не требуется.,Лёгкий fine-tuning готовой модели на небольшом...,"Подготовка/очистка датасета, SFT/LoRA, несколь...","Большой специализированный датасет, full/advan..."
26,Модели и ML,Кастомные ML-модели помимо LLM,Не нужны.,Один готовый классификатор/embedding/reranker ...,Одна или несколько обучаемых моделей для inten...,"Набор специализированных моделей с MLOps, onli..."
27,Модели и ML,Мультимодальность: изображения,Изображения не используются.,Пользователь может приложить изображение; анал...,"Несколько типов изображений, OCR+vision, struc...","Специализированное computer vision, высокое ка..."
28,Качество и аналитика,Автоматическая оценка качества (Evals),Не предусмотрена.,Небольшой ручной test set и базовые regression...,"Набор offline evals: correctness, groundedness...",Полноценная evaluation platform: большие gold ...
29,Качество и аналитика,Feedback пользователей,Не собирается.,Like/dislike и текстовый комментарий.,"Категоризация причин, связь feedback с trace, ...","Active learning loop, приоритизация ошибок, hu..."
30,Качество и аналитика,Продуктовая аналитика,Не нужна.,"Базовые метрики: число диалогов, пользователей...","Воронки, intents, resolution rate, escalation ...","Сложная аналитика ROI и качества, causal/A-B e..."
31,Инфраструктура,Развертывание,Отдельное развертывание не требуется / прототи...,"Один cloud environment, managed services, Docker.","Dev/Test/Prod, Kubernetes или корпоративное об...","On-prem/air-gapped или multi-region, HA/DR, ст..."
32,Инфраструктура,Масштаб / нагрузка,Только демонстрационный прототип.,"До сотен активных пользователей, небольшая пар...","Тысячи пользователей, десятки/сотни одновремен...",Очень высокая нагрузка/24×7: тысячи одновремен...
33,Инфраструктура,Latency / real-time требования,Нет специальных требований.,Обычный чат; приемлемо несколько секунд на ответ.,"Streaming, first-token latency target, быстрый...","Жёсткие real-time SLA, interruption/barge-in, ..."
34,Инфраструктура,Отказоустойчивость и SLA,SLA не задан.,"Best effort, обычные managed-service гарантии.","Формальный SLA, health checks, retries, резерв...","Критичный 24×7 сервис: multi-AZ/region, DR pla..."
35,Инфраструктура,Наблюдаемость / мониторинг,Только базовые application logs.,"Метрики ошибок, latency, token/cost usage.","Distributed traces для LLM/RAG/tools, dashboar...","Полная enterprise observability, SLO/error bud..."
36,Инфраструктура,Оптимизация стоимости LLM,Не требуется.,Простые лимиты токенов и выбор недорогой модели.,"Model routing, caching, prompt compression, bu...","Динамическая оптимизация model mix, semantic c..."
37,Enterprise и эксплуатация,Админ-панель,Не нужна.,"Минимальные настройки: промпт, включение функц...","Управление KB, пользователями, ролями, каналам...",Полноценный no/low-code control plane: workflo...
38,Enterprise и эксплуатация,Мультитенантность,Один заказчик/контур.,Несколько подразделений с общей инфраструктуро...,"Полноценные tenant settings, отдельные KB/прав...","Строгая tenant isolation, отдельные ключи/данн..."
39,Enterprise и эксплуатация,Конфигурируемость без разработки,Не требуется.,Несколько параметров в конфиге.,"UI для промптов, источников знаний, политик и ...","No-code/low-code конструктор ассистентов, work..."
40,Enterprise и эксплуатация,CI/CD и управление версиями,Ручное развертывание прототипа.,Обычный Git + простой pipeline.,"Раздельные environments, automated tests/evals...","Enterprise release management: approvals, cana..."
41,Enterprise и эксплуатация,Документация и обучение команды заказчика,Не требуется.,Краткая инструкция пользователя/администратора.,"Техническая и пользовательская документация, r...",Полный knowledge transfer: архитектурная докум...

In [3]:
api_key = config.get("OPENAI_API_KEY") or os.getenv("OPENAI_API_KEY")
if not api_key:
    raise RuntimeError("Добавьте OPENAI_API_KEY в .env в корне репозитория или evalutator/.env.")
client = OpenAI(api_key=api_key, timeout=180.0, max_retries=3)
results = evaluate(client, MODEL, menu, text, batch_size=BATCH_SIZE, max_spec_chars=MAX_SPEC_CHARS)
# Сохраняем оценки ДО запроса заключения: ошибка второго этапа не потеряет разметку.
csv_path = save_results(results, RUN_DIR, TZ_PATH.stem)
print(f"Разметка сохранена: {csv_path}")
display(results)
display(__import__("pandas").DataFrame([statistics(results)]))

Размечено 7 из 42 пунктов
Размечено 14 из 42 пунктов
Размечено 21 из 42 пунктов
Размечено 28 из 42 пунктов
Размечено 35 из 42 пунктов
Размечено 42 из 42 пунктов
Разметка сохранена: /home/elwis/Projects/case-finder/evaluator/results/20261028T165535Z_f5dd596b/ТЗ - Сервис для создания виртуальных ассистентов (Electra 2.0)_оценка.csv

,Блок,Компонент,Оценка,Уверенность,Коментарий
0,Каналы и интерфейсы,Текстовый веб-чат,medium,0.90,По пункту 1.2 описана работа текстового веб-ча...
1,Каналы и интерфейсы,Мессенджеры и внешние каналы,small,0.95,"Пункт 7.3 указывает, что интеграции с мессендж..."
2,Каналы и интерфейсы,Мобильное приложение / SDK,отсутствует,0.95,В описании нет упоминаний или требований по мо...
3,Голос,Голосовой ввод (Speech-to-Text),отсутствует,0.95,"В разделе 1.3 указано, что поддержка голосовых..."
4,Голос,Голосовой вывод (Text-to-Speech),отсутствует,0.95,"Пункт 1.3 прямо говорит, что голосовые ответы ..."
5,Голос,Телефонный канал / телефония,отсутствует,1.00,В тексте нет упоминаний о телефонном канале ил...
6,LLM и диалог,Базовая LLM / генерация ответов,small,0.90,В ТЗ не указано использование LLM для генераци...
7,LLM и диалог,Промптинг и управление поведением,small,0.90,В ТЗ описаана система на On-Prem и Cloud с баз...
8,LLM и диалог,Управление контекстом диалога,medium,0.85,"В ТЗ указано, что диалоги имеют контекст: хран..."
9,LLM и диалог,Сценарии / state machine,medium,0.90,"ТЗ описывает многошаговые сценарии, состояния ..."
10,LLM и диалог,Мультиязычность,medium,0.80,"В ТЗ указана мультиязычность, возможность смен..."
11,Знания и RAG,База знаний / RAG,medium,0.75,ТЗ предполагает работу с большим количеством с...
12,Знания и RAG,Источники данных для базы знаний,medium,0.75,В ТЗ нет детального описания интеграции многих...
13,Знания и RAG,Обработка документов,small,0.70,В ТЗ нет специальных требований к сложной обра...
14,Знания и RAG,Цитирование и доказательность ответов,small,0.90,В ТЗ отмечены ссылки на документы с описанием ...
15,Интеграции и действия,Интеграции с внешними системами,medium,0.85,В ТЗ описаны интеграции с множеством систем: A...
16,Интеграции и действия,Выполнение действий от имени пользователя,medium,0.90,Возможность выполнения действий от имени польз...
17,Интеграции и действия,Agentic tool use / выбор инструментов,medium,0.80,В ТЗ описаны возможности выбора и изменения па...
18,Интеграции и действия,Human handoff / оператор,small,0.85,В ТЗ содержится описание минимальной поддержки...
19,Персонализация,Профиль и персонализация пользователя,medium,0.90,Персонализация реализована на уровне разных ро...
20,Персонализация,Роли и права доступа,medium,0.95,В ТЗ подробно описана многоуровневая ролевая м...
21,Безопасность,Защита от prompt injection / data leakage,medium,0.90,В ТЗ указано требование по безопасности и защи...
22,Безопасность,PII / конфиденциальные данные,medium,0.85,"В разделе Безопасность указано, что персональн..."
23,Безопасность,Контент-фильтрация / moderation,small,0.80,В ТЗ нет прямого требования к контент-фильтрац...
24,Безопасность,Аудит действий,medium,0.90,ТЗ содержит требование ведения журналов действ...
25,Модели и ML,Fine-tuning / дообучение LLM,medium,0.85,"В ТЗ описано, что редактор и Data Scientist мо..."
26,Модели и ML,Кастомные ML-модели помимо LLM,medium,0.85,ТЗ описывает наличие нескольких ML-моделей: кл...
27,Модели и ML,Мультимодальность: изображения,small,0.75,"В ТЗ указано, что клиент может отправлять файл..."
28,Качество и аналитика,Автоматическая оценка качества (Evals),medium,0.90,В ТЗ описаны функции аналитика по запуску тест...
29,Качество и аналитика,Feedback пользователей,small,0.85,В ТЗ есть описание ручной разметки с метками T...
30,Качество и аналитика,Продуктовая аналитика,medium,0.90,В ТЗ есть метрики качества: доля автоматизации...
31,Инфраструктура,Развертывание,medium,0.85,В ТЗ описано наличие docker-контейнеров и возм...
32,Инфраструктура,Масштаб / нагрузка,medium,0.80,"В ТЗ указано требование масштабируемости, обра..."
33,Инфраструктура,Latency / real-time требования,small,0.70,В ТЗ присутствуют требования к голосовому отве...
34,Инфраструктура,Отказоустойчивость и SLA,medium,0.80,"В ТЗ есть требования отказоустойчивости, восст..."
35,Инфраструктура,Наблюдаемость / мониторинг,medium,0.90,В ТЗ указано использование системы логирования...
36,Инфраструктура,Оптимизация стоимости LLM,small,0.80,В ТЗ отсутствуют прямые описания оптимизации с...
37,Enterprise и эксплуатация,Админ-панель,medium,0.95,ТЗ подробно описывает наличие административног...
38,Enterprise и эксплуатация,Мультитенантность,medium,0.90,Система поддерживает несколько ролей пользоват...
39,Enterprise и эксплуатация,Конфигурируемость без разработки,large,0.95,ТЗ содержит обширное описание широких возможно...
40,Enterprise и эксплуатация,CI/CD и управление версиями,small,0.70,В ТЗ описывается управление версиями баз знани...
41,Enterprise и эксплуатация,Документация и обучение команды заказчика,medium,0.85,Приведены требования к инструкции пользователя...

,Всего,Успешно проставлено,Не определены,отсутствует,small,medium,large
0,42,42,0,4,12,25,1

In [4]:
summary = summarize(client, MODEL, menu, text, results)
additions, report_path = save_summary(summary, results, RUN_DIR, TZ_PATH.stem)
print("Общее заключение\n")
print(summary.conclusion)
print("\nВопросы для уточнения:")
for question in summary.questions:
    print("•", question)
print("\nРекомендуемые дополнения меню с критериями по категориям:")
if additions.empty:
    print("Дополнения не требуются.")
else:
    with __import__("pandas").option_context("display.max_colwidth", None):
        display(additions)
print(f"\nЗаключение: {report_path}")

Общее заключение

Данное ТЗ описывает комплексную систему для создания виртуальных ассистентов с функционалом On-Prem/Cloud, поддержкой ролей, управления чатботами и их контентом. Многие аспекты покрыты на среднем уровне, например интеграции, сценарии, аналитика, безопасность и инфраструктура. В тоже время мультиязычность и конфигурируемость хорошо проработаны, обеспечивая высокий уровень удобства. Голосовые каналы, мобильные приложения, полноценные LLM, телефонный канал и продвинутая автоматизация CI/CD отсутствуют или представлены на базовом уровне.

Вопросы для уточнения:
• Подтверждается ли необходимость поддержки голосового ввода (speech-to-text) и голосового ответа (text-to-speech) в ближайших этапах?
• Требуется ли интеграция с корпоративными IAM через SSO/OIDC/SAML?
• Нужна ли полноценная автоматизация CI/CD с управлением версиями и откатами на уровне системы, а не вручную?
• Требуется ли поддержка масштабных голосовых звонков и интеграция с контакт-центром (телефония)?
• Какой объем и требования к оптимизации стоимости работы LLM предполагается в будущем?
• Нужен ли кастомный мультиязычный голосовой движок с дообучением?
• Нужно ли добавить поддержку мобильных приложений или SDK?

Рекомендуемые дополнения меню с критериями по категориям:

,Блок,Компонент,Обоснование,Отсутствует,Small,Medium,Large
0,Голос,Голосовой ввод (Speech-to-Text),"В ТЗ голосовой ввод отсутствует, но может потребоваться для поддержки голосового общения с чатботом.","Голосовой ввод не реализован, голосовые запросы не поддерживаются.","Интеграция стандартного SaaS STT сервиса без обучения, несколько языков.","On-prem/Private Cloud с повышенными требованиями latency, словарём терминов.","Сложный On-prem движок с высокими SLA, адаптацией, потоковой обработкой и многоканальным diarization."
1,Голос,Голосовой вывод (Text-to-Speech),"В ТЗ голосовой вывод отсутствует, но клиент должен получить голосовой ответ в будущем.",Голосовой вывод не поддерживается.,Использование стандартного SaaS TTS с готовыми голосами.,On-prem или кастомный голос с voice cloning и streaming.,"Брендовый голос с эмоциями, многъязычностью и низкой задержкой."
2,Каналы и интерфейсы,Мобильное приложение / SDK,"В ТЗ отсутствует упоминание мобильного приложения или SDK, но такие интеграции могут понадобиться для удобства пользователей.",Отсутствует поддержка мобильных приложений и SDK.,Интеграция через WebView или простой SDK.,Нативные мобильные приложения с push-уведомлениями и микрофоном.,Отдельный мобильный UX с offline поддержкой и собственным SDK.

Заключение: /home/elwis/Projects/case-finder/evaluator/results/20261028T165535Z_f5dd596b/ТЗ - Сервис для создания виртуальных ассистентов (Electra 2.0)_заключение.txt

Файлы сохраняются в `evalutator/results/<идентификатор запуска>/`:
- `*_оценка.csv`: **Блок, Компонент, Оценка, Уверенность, Коментарий** (написание последнего столбца сохранено по запросу).
- `*_заключение.txt`: заключение, статистика, вопросы и расшифровка дополнений.
- `*_дополнения_меню.csv`: новые компоненты с определениями отсутствует/small/medium/large.

CSV имеет кодировку UTF-8 с BOM для Excel. Результаты и `.env` исключены из Git.
При отказе API, ошибке структуры ответа, пропусках или повторах ID выполнение останавливается с ошибкой;
техническая ошибка не превращается в оценку «не определено». После ошибки заключения можно повторить только последнюю кодовую ячейку.

In [ ]:
!pip install -U openai